### ISSUE TITLE
hó

### ISSUE THREAD

**Issue by khun2** [ESzPa/Karesz-sharp#1]
"hó" színű kavicsokbol nincsen végtelen alapbol de egy very easy fix
![image](https://github.com/ESzPa/super_oopkaresz/assets/134009911/8f429d7a-dee7-41e1-bb5f-054dbed8a819)
itt az alap
![image](https://github.com/ESzPa/super_oopkaresz/assets/134009911/fe9d361e-84fa-4aa1-86f1-a5f492d9d2fa)
itt a fixed

**Comment by ESzPa** [comment]
Okay master<sup><sup><sup>onii-chan</sup></sup></sup>  
**https://t.ly/7IIMq**
